// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.shopzilla.publisher.rich.client.managed.request;

import com.shopzilla.publisher.rich.shared.gae.MakesGaeRequests;
import com.shopzilla.publisher.rich.shared.scaffold.ScaffoldRequestFactory;

public interface ApplicationRequestFactory extends ScaffoldRequestFactory, MakesGaeRequests {

    ProductRequest productRequest();
}
