// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.shopzilla.publisher.rich.client.managed.request;

import com.google.gwt.requestfactory.shared.InstanceRequest;
import com.google.gwt.requestfactory.shared.Request;
import com.google.gwt.requestfactory.shared.RequestContext;
import com.google.gwt.requestfactory.shared.ServiceName;
import org.springframework.roo.addon.gwt.RooGwtMirroredFrom;

@RooGwtMirroredFrom("com.shopzilla.publisher.rich.domain.Product")
@ServiceName("com.shopzilla.publisher.rich.domain.Product")
public interface ProductRequest extends RequestContext {

    abstract InstanceRequest<com.shopzilla.publisher.rich.client.managed.request.ProductProxy, java.lang.Void> persist();

    abstract InstanceRequest<com.shopzilla.publisher.rich.client.managed.request.ProductProxy, java.lang.Void> remove();

    abstract Request<java.lang.Long> countProducts();

    abstract Request<java.util.List<com.shopzilla.publisher.rich.client.managed.request.ProductProxy>> findAllProducts();

    abstract Request<com.shopzilla.publisher.rich.client.managed.request.ProductProxy> findProduct(Long id);

    abstract Request<java.util.List<com.shopzilla.publisher.rich.client.managed.request.ProductProxy>> findProductEntries(int firstResult, int maxResults);
}
