// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.shopzilla.publisher.rich.client.managed.ui;

import com.google.gwt.text.shared.AbstractRenderer;
import com.shopzilla.publisher.rich.client.managed.request.ApplicationEntityTypesProcessor;
import com.shopzilla.publisher.rich.client.managed.request.ProductProxy;
import com.shopzilla.publisher.rich.client.scaffold.place.ProxyListPlace;

public abstract class ApplicationListPlaceRenderer_Roo_Gwt extends AbstractRenderer<ProxyListPlace> {

    public String render(ProxyListPlace object) {
        return new ApplicationEntityTypesProcessor<String>() {

            @Override
            public void handleProduct(ProductProxy isNull) {
                setResult("Products");
            }
        }.process(object.getProxyClass());
    }
}
