// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.shopzilla.publisher.rich.client.managed.ui;

import com.google.gwt.core.client.GWT;
import com.google.gwt.dom.client.Element;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.HasClickHandlers;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HTMLPanel;
import com.google.gwt.user.client.ui.Widget;
import com.shopzilla.publisher.rich.client.managed.request.ProductProxy;
import com.shopzilla.publisher.rich.client.scaffold.place.ProxyDetailsView;

public abstract class ProductMobileDetailsView_Roo_Gwt extends Composite implements ProxyDetailsView<ProductProxy> {

    @UiField
    Element id;

    @UiField
    Element version;

    @UiField
    Element title;

    @UiField
    Element url;

    @UiField
    Element imgUrl;

    ProductProxy proxy;

    public void setValue(ProductProxy proxy) {
        this.proxy = proxy;
        id.setInnerText(proxy.getId() == null ? "" : String.valueOf(proxy.getId()));
        version.setInnerText(proxy.getVersion() == null ? "" : String.valueOf(proxy.getVersion()));
        title.setInnerText(proxy.getTitle() == null ? "" : String.valueOf(proxy.getTitle()));
        url.setInnerText(proxy.getUrl() == null ? "" : String.valueOf(proxy.getUrl()));
        imgUrl.setInnerText(proxy.getImgUrl() == null ? "" : String.valueOf(proxy.getImgUrl()));
    }
}
