// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.

package com.shopzilla.publisher.rich.client.managed.ui;

import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.safehtml.shared.SafeHtml;
import com.google.gwt.safehtml.shared.SafeHtmlBuilder;
import com.google.gwt.safehtml.shared.SafeHtmlUtils;
import com.google.gwt.text.client.DateTimeFormatRenderer;
import com.google.gwt.text.shared.AbstractRenderer;
import com.google.gwt.text.shared.AbstractSafeHtmlRenderer;
import com.google.gwt.text.shared.Renderer;
import com.google.gwt.text.shared.SafeHtmlRenderer;
import com.shopzilla.publisher.rich.client.managed.request.ProductProxy;
import com.shopzilla.publisher.rich.client.scaffold.ScaffoldMobileApp;
import com.shopzilla.publisher.rich.client.scaffold.ui.MobileProxyListView;
import java.util.HashSet;
import java.util.Set;

public abstract class ProductMobileListView_Roo_Gwt extends MobileProxyListView<ProductProxy> {

    protected Set<String> paths = new HashSet<String>();

    public ProductMobileListView_Roo_Gwt(String buttonText, SafeHtmlRenderer<com.shopzilla.publisher.rich.client.managed.request.ProductProxy> renderer) {
        super(buttonText, renderer);
    }

    public void init() {
        paths.add("title");
        paths.add("url");
    }
}
